//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Agro
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public korisnik()
        {
            this.otpremnicas = new HashSet<otpremnica>();
            this.ponudas = new HashSet<ponuda>();
            this.primkas = new HashSet<primka>();
            this.narudzbas = new HashSet<narudzba>();
        }
    
        public int korisnik_id { get; set; }
        public string email { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public int tip_id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string tekuci_racun { get; set; }
        public string adresa { get; set; }
        public int radno_mjesto_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<otpremnica> otpremnicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponuda> ponudas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<primka> primkas { get; set; }
        public virtual radno_mjesto radno_mjesto { get; set; }
        public virtual tip_korisnika tip_korisnika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narudzba> narudzbas { get; set; }
    }
}
