//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Agro
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class narudzba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public narudzba()
        {
            this.stavke_na_narudzbi = new HashSet<stavke_na_narudzbi>();
        }

        [DisplayName("Narudzba")]
        public int narudzba_id { get; set; }
        [DisplayName("Dobavljac")]
        public int dobavljac_id { get; set; }
        [DisplayName("Cijena")]
        public double cijena { get; set; }
        [DisplayName("Korisnik")]
        public int korisnik_id { get; set; }
        [DisplayName("Datum izdavanja")]
        public Nullable<System.DateTime> datum_izdavanja { get; set; }
        [DisplayName("Status")]
        public string status { get; set; }
        [DisplayName("Napomena")]
        public string napomena { get; set; }

        [DisplayName("Dobavljac")]
        public virtual dobavljac dobavljac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_na_narudzbi> stavke_na_narudzbi { get; set; }
        [DisplayName("Korisnik")]
        public virtual korisnik korisnik { get; set; }
    }
}
