//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Agro
{
    using System;
    using System.Collections.Generic;
    
    public partial class stroj_na_skladistu
    {
        public int stroj_id { get; set; }
        public int skladiste_id { get; set; }
        public int kolicina { get; set; }
    
        public virtual katalog_strojeva katalog_strojeva { get; set; }
        public virtual skladiste skladiste { get; set; }
    }
}
