//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Agro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI20_024_DBEntities : DbContext
    {
        public PI20_024_DBEntities()
            : base("name=PI20_024_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dobavljac> dobavljacs { get; set; }
        public virtual DbSet<katalog_strojeva> katalog_strojeva { get; set; }
        public virtual DbSet<klijent> klijents { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<narudzba> narudzbas { get; set; }
        public virtual DbSet<otpremnica> otpremnicas { get; set; }
        public virtual DbSet<ponuda> ponudas { get; set; }
        public virtual DbSet<primka> primkas { get; set; }
        public virtual DbSet<radno_mjesto> radno_mjesto { get; set; }
        public virtual DbSet<skladiste> skladistes { get; set; }
        public virtual DbSet<stavke_na_narudzbi> stavke_na_narudzbi { get; set; }
        public virtual DbSet<stavke_na_otpremnici> stavke_na_otpremnici { get; set; }
        public virtual DbSet<stavke_na_ponudi> stavke_na_ponudi { get; set; }
        public virtual DbSet<stavke_na_primci> stavke_na_primci { get; set; }
        public virtual DbSet<stroj_na_skladistu> stroj_na_skladistu { get; set; }
        public virtual DbSet<tip_korisnika> tip_korisnika { get; set; }
        public virtual DbSet<ured> ureds { get; set; }
    }
}
