//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Agro
{
    using System;
    using System.Collections.Generic;
    
    public partial class katalog_strojeva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public katalog_strojeva()
        {
            this.stavke_na_narudzbi = new HashSet<stavke_na_narudzbi>();
            this.stavke_na_otpremnici = new HashSet<stavke_na_otpremnici>();
            this.stavke_na_ponudi = new HashSet<stavke_na_ponudi>();
            this.stavke_na_primci = new HashSet<stavke_na_primci>();
            this.stroj_na_skladistu = new HashSet<stroj_na_skladistu>();
        }
    
        public int stroj_id { get; set; }
        public string naziv { get; set; }
        public string vrsta { get; set; }
        public string model { get; set; }
        public string opis { get; set; }
        public double cijena { get; set; }
        public int dobavljac_id { get; set; }
    
        public virtual dobavljac dobavljac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_na_narudzbi> stavke_na_narudzbi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_na_otpremnici> stavke_na_otpremnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_na_ponudi> stavke_na_ponudi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_na_primci> stavke_na_primci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stroj_na_skladistu> stroj_na_skladistu { get; set; }
    }
}
