//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Agro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponuda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ponuda()
        {
            this.stavke_na_ponudi = new HashSet<stavke_na_ponudi>();
        }
    
        public int ponuda_id { get; set; }
        public int korisnik_id { get; set; }
        public string naziv { get; set; }
        public double cijena { get; set; }
        public System.DateTime datum_kreiranja { get; set; }
        public int klijent_id { get; set; }
    
        public virtual klijent klijent { get; set; }
        public virtual korisnik korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavke_na_ponudi> stavke_na_ponudi { get; set; }
    }
}
